spring.application.name=ChatApplication
server.port=8083
server.servlet.context-path=/chat
server.address=192.168.1.183

#mysql Connection
spring.datasource.url=jdbc:mysql://192.168.1.18:3306/issueDetails
spring.datasource.username=root
spring.datasource.password=BeasCf345@Kol2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate & Jpa Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#url where the client will connect
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
