#mysql Connection
server.port=8083
spring.datasource.url=jdbc:mysql://192.168.1.18:3306/issueDetails
spring.datasource.username=root
spring.datasource.password=BeasCf345@Kol2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
my.env.name=PROD